modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/ThreeTAG/Palladium/issues"

[[mods]]
modId = "palladium"
version = "${version}"
displayName = "Palladium"
authors = "Lucraft"
description = '''
Core mod for all ThreeTAG mods.
'''
logoFile = "palladium_banner.png"
logoBlur = false
displayURL = "https://www.curseforge.com/minecraft/mc-mods/palladium"
updateJSONURL = "https://api.modrinth.com/updates/threetag-palladium/forge_updates.json"

[modproperties.palladium]
catalogueImageIcon = "palladium_icon.png"

[[dependencies.palladium]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladium]]
modId = "palladiumcore"
mandatory = true
versionRange = "[1.20.1-1.6.0.0,)"
ordering = "AFTER"
side = "BOTH"