modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/ThreeTAG/Palladium/issues"

[[mods]]
modId = "palladium"
version = "${version}"
displayName = "Palladium"
authors = "Lucraft"
description = '''
Core mod for all ThreeTAG mods.
'''
logoFile = "palladium_banner.png"
logoBlur = false
displayURL = "https://www.curseforge.com/minecraft/mc-mods/palladium"

[modproperties.palladium]
catalogueImageIcon = "palladium_icon.png"

[[dependencies.palladium]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladium]]
modId = "palladiumcore"
mandatory = true
versionRange = "[1.19.2-1.0.6,)"
ordering = "AFTER"
side = "BOTH"