modLoader="javafml"
loaderVersion="[34,)"
authors="Lucraft, Nictogen"
license="All rights reserved"

[[mods]]
modId="threecore"
version="${file.jarVersion}"
displayName="ThreeCore"
logoFile="threecore.png"
description='''
Core mod for all ThreeTAG mods.
'''

[[dependencies.threecore]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"