modLoader="javafml"
loaderVersion="[28,)"
authors="Lucraft, Nictogen"

[[mods]]
modId="threecore"
version="${file.jarVersion}"
displayName="ThreeCore"
logoFile="threecore.png"
description='''
Core mod for all ThreeTAG mods.
'''

[[dependencies.threecore]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"