modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/ThreeTAG/Palladium/issues"

[[mods]]
modId = "palladium"
version = "${version}"
displayName = "Palladium"
authors = "Lucraft"
description = '''
Core mod for all ThreeTAG mods.
'''
logoFile = "palladium_banner.png"
logoBlur = false
displayURL = "https://modrinth.com/project/threetag-palladium"
updateJSONURL = "https://squirrelcontrol.threetag.net/api/forge_updates/threetag-palladium"

[modproperties.palladium]
catalogueImageIcon = "palladium_icon.png"

[[dependencies.palladium]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladium]]
modId = "palladiumcore"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"
